version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/rails
    ports:
      - "3001:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/test_api_development
    depends_on:
      - db
    command: bundle exec rails server -b 0.0.0.0 -p 3000

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_api_development
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
